### ISSUE TITLE
mkdocs serve fails with "permission denied" on Windows

### ISSUE THREAD

**Issue by asjohnston-asf** [ASFHyP3/hyp3-docs#70]
Running `mkdocs serve` in a Windows environment fails with:
```
Copying image: https://img.shields.io/pypi/l/hyp3_sdk.svg to C:\Users\hjkristenson\PycharmProjects\hyp3-docs\docs\using\sdk\gen_\https:\img.shields.io\pypi\l\hyp3_sdk.svg
ERROR   -  Error reading page 'using\sdk.md': [WinError 123] The filename, directory name, or volume label syntax is incorrect: '/tmp/2ad0de8a3e5843648186ad4234bfc271/C:'

[WinError 123] The filename, directory name, or volume label syntax is incorrect: '/tmp/2ad0de8a3e5843648186ad4234bfc271/C:'
```

This is an issue with the gitsnippet plugin.  As a workaround, removing the gitsnippet calls from the three markdown pages that reference it allows the `mkdocs serve` command to succeed, but the built site will be missing the desired content on those pages.

https://github.com/ASFHyP3/hyp3-docs/blob/develop/docs/tools/arcgis_toolbox.md
https://github.com/ASFHyP3/hyp3-docs/blob/develop/docs/tools/asf_tools.md
https://github.com/ASFHyP3/hyp3-docs/blob/develop/docs/using/sdk.md

**Comment by jhkennedy** [comment]
Hmm, that's not great. I've thought about changing it over to a [MkDocs Macro](https://pypi.org/project/mkdocs-macros-plugin/) so we can have some more control over the code, but the underlying issue might still be present if we don't engineer for it

CC: @Jlrine2 just making sure you see this because i can't open an issue in your fork
